### ISSUE TITLE
Create and publish a release-4.9 branch

### ISSUE THREAD

**Issue by fidencio** [openshift/sandboxed-containers-operator#157]
**Description**

There's no release-4.9 branch, even with OpenShift 4.9 being released  on Oct, 18th 2021.

**Steps to reproduce the issue:**
1. Open a browser
2. Go to  https://github.com/openshift/sandboxed-containers-operator
3. Check the branches

**Describe the results you received:**

The newest release-x.y branch is 4.8.

**Describe the results you expected:**

A release-4.9 branch should be present and published, considering `master` is being used for the "under development OCP 4.10".

**Additional information you deem important (e.g. issue happens only occasionally):**

Not relevant

**Output of `oc describe kataconfig <your-kataconfig>`:**

```
Not relevant
```

**Additional environment details (platform, options, etc.):**

Not relevant

**Comment by bpradipt** [comment]
Hi @fidencio, thanks for raising the issue. 
Starting from 4.9, switched to release-x.y based on operator version instead of OpenShift versions.
First one is release-1.1 which should work for 4.9/4.10..

However I see that deploy.yaml is not existing for release-1.1 branch. This is something that needs fixing.

Also I think README should be updated to reflect the release branch name change. Sorry about it. Will create a PR soon.

**Comment by fidencio** [comment]
> Also I think README should be updated to reflect the release branch name change.

Oh yeah, anyone who's outside of the internal team meetings will not be able to associate that the release-1.1 should be used with OCP 4.9 / 4.10, mainly with the existing release-4.6, and release-4.7 branches there.

> Sorry about it. Will create a PR soon.

No problemo, thanks for the quick reply.

**Comment by bpradipt** [comment]
Updated readme reflects the branch name change now. Closing this issue.
