### ISSUE TITLE
Modified files after building

### ISSUE THREAD

**Issue by cpmeadors** [openshift/sandboxed-containers-operator#209]
After running docker-build, bundle-build, catalog-build  There are a number of modified files.  Are these safe if they accidentally get checked in?  Should they be getting updated? Should they be updated in the repo?

bundle.Dockerfile
config/crd/bases/kataconfiguration.openshift.io_kataconfigs.yaml
config/rbac/role.yaml
config/webhook/manifests.yaml
bundle/manifests/kataconfiguration.openshift.io_kataconfigs.yaml
bundle/metadata/annotations.yaml

**Comment by bpradipt** [comment]
Files under `config/` typically get updated if there are changes to the API, sdk, or when building your own operator image.
The changes due to API or sdk are core code related changes and hence needs to be tracked. 

Files under `bundle/` are generated from `config/` on execution of `make bundle`. The reason for checking this is to get a repeatable build of the bundle and catalog when using the upstream code without regenerating the bundle. We can think about completely removing the `bundle` directory.

One option is to provide git instructions to not track the local changes if needed by the developer.

**Comment by cpmeadors** [comment]
Based on the operator-sdk docs, "make generate" creates:

api/v1/zz_generated.deepcopy.go

"make manifests" creates: 

config/crd/bases/kataconfiguration.openshift.io_kataconfigs.yaml
config/rbac/role.yaml
config/webhook/manifests.yaml

"make bundle" generates

bundle.Dockerfile
bundle/metadata/annotations.yaml
bundle

Why should any of these files be tracked?  The files that define the generation of them are tracked.
